add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "cyan bold"
truncation_length = 0

[username]
style_user = "purple bold"
style_root = "black bold"
show_always = true

[cmd_duration]
style = "purple bold"
